### ISSUE TITLE
issue with setup.py

### ISSUE THREAD

**Issue by mikkokotila** [infectious/adstxtcrawler#2]
It seems there is some syntax in setup.py which results in an error when trying to install on some systems (some system works strangely even the python version is same).

```
root@NC-PH-1753-43:~# source env/bin/activate
(env) root@NC-PH-1753-43:~# pip install git+https://github.com/infectious/adstxtcrawler.git
Collecting git+https://github.com/infectious/adstxtcrawler.git
  Cloning https://github.com/infectious/adstxtcrawler.git to /tmp/pip-R6VKBV-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-R6VKBV-build/setup.py", line 10
        def parse_reqs(requirements_file: str) -> List[str]:
                                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-R6VKBV-build/
(env) root@NC-PH-1753-43:~# 

```

**Comment by Poogles** [comment]
These are type annotations, the crawler only supports 3.6 and up.

**Comment by mikkokotila** [comment]
That's from python 3.6

EDIT: let me check later, it might be the issue where even though the env is 3.6, the default python is still something else.

**Comment by Poogles** [comment]
Try adding a `import sys; print(sys.version)` in the setup.py and that might help you debug it.

It might be also something aloof with the path, try `which python` inside the venv to ensure you're pointing to the right place.
